"""HDFC bank statement PDF parser.

Uses page-text extraction (not extract_tables) because HDFC's PDF layout makes
pdfplumber return one mega-row per page with newline-separated values that
do not align across columns when narrations span multiple lines.

Strategy:
  1. Unlock the PDF if password-protected.
  2. For each page, extract_text() and split into lines.
  3. A transaction begins at any line whose first token matches DD/MM/YY.
  4. Subsequent lines without a leading date are narration continuation,
     UNLESS the line looks like a page footer (account header, HDFC boilerplate,
     statement-summary text, page numbers) -- in which case the current
     transaction is closed and the rest of the page is skipped until the next
     real transaction line.
"""
from __future__ import annotations

import re
from datetime import datetime, date
from pathlib import Path

import pdfplumber

from app.parsers.base import BankAdapter, ParseResult, ParsedTransaction
from app.utils.pdf_unlock import unlock_pdf


DATE_PATTERN = re.compile(r"^(\d{2}/\d{2}/\d{2})\b")
AMOUNT_PATTERN = re.compile(r"^[\d,]+\.\d{2}$")

# Lines that mark the start of footer / boilerplate / next-page-header content.
# Once we see one of these, we stop appending narration to the current row
# and skip lines until we find a new date-prefixed transaction line.
STOP_KEYWORDS = (
    "STATEMENT SUMMARY",
    "STATEMENTSUMMARY",
    "Opening Balance",
    "OpeningBalance",
    "Generated On",
    "GeneratedOn",
    "Generated By",
    "GeneratedBy",
    "Requesting Branch",
    "RequestingBranch",
    "Page No",
    "PageNo",
    "HDFC BANK LIMITED",
    "HDFCBANKLIMITED",
    "*Closing balance",
    "*Closingbalance",
    "Contents of this statement",
    "Contentsofthisstatement",
    "State account branch",
    "Stateaccountbranch",
    "HDFC Bank GSTIN",
    "HDFCBankGSTIN",
    "Registered Office Address",
    "RegisteredOfficeAddress",
    "This is a computer generated",
    "Thisisacomputergenerated",
    "Account Branch",
    "AccountBranch",
    "JOINT HOLDERS",
    "JOINTHOLDERS",
    "Nomination",
    "From :",  # "From : 01/04/2026 To : 30/04/2026"
    "From:",
    "MR LOKENDRA",  # account holder name -- generalize to any header line, see below
    "Statement of account",
    "Statementof account",
    "Date Narration",  # column header row
    "DateNarration",
    "RTGS/NEFT",
    "Branch Code",
    "BranchCode",
    "Account Type",
    "AccountType",
    "Account No",
    "AccountNo",
    "A/C Open",
    "A/COpen",
    "Account Status",
    "AccountStatus",
    "Cust ID",
    "CustID",
    "OD Limit",
    "ODLimit",
    "Phone no",
    "Phoneno",
)


def _parse_date(s: str) -> date:
    return datetime.strptime(s, "%d/%m/%y").date()


def _to_amount(s: str) -> float:
    return float(s.replace(",", ""))


def _is_amount(tok: str) -> bool:
    return bool(AMOUNT_PATTERN.match(tok))


def _is_stop_line(line: str) -> bool:
    """A line is a stop marker if it contains any STOP_KEYWORD as a substring."""
    return any(kw in line for kw in STOP_KEYWORDS)


def _parse_txn_line(line: str) -> dict | None:
    """Parse a single transaction line. Returns a dict or None if malformed."""
    tokens = line.split()
    if len(tokens) < 5:
        return None

    m = DATE_PATTERN.match(tokens[0])
    if not m:
        return None
    txn_date = _parse_date(tokens[0])

    if not _is_amount(tokens[-1]):
        return None
    closing_balance = _to_amount(tokens[-1])

    if not _is_amount(tokens[-2]):
        return None
    txn_amount = _to_amount(tokens[-2])

    # Walk back to find the value_date
    value_date_idx = None
    for i in range(len(tokens) - 3, 0, -1):
        if DATE_PATTERN.match(tokens[i]):
            value_date_idx = i
            break
    if value_date_idx is None or value_date_idx == 0:
        return None
    value_date = _parse_date(tokens[value_date_idx])

    reference_id = tokens[value_date_idx - 1] if value_date_idx >= 2 else None
    narration_start = " ".join(tokens[1 : value_date_idx - 1])

    return {
        "txn_date": txn_date,
        "value_date": value_date,
        "reference_id": reference_id,
        "narration_first_line": narration_start,
        "amount": txn_amount,
        "closing_balance": closing_balance,
    }


def _infer_directions(rows: list[dict], opening_balance: float | None) -> None:
    """Set 'direction' on every row by comparing closing balances."""
    prev_balance = opening_balance
    for r in rows:
        if prev_balance is None:
            r["direction"] = "debit"
        else:
            delta = round(r["closing_balance"] - prev_balance, 2)
            r["direction"] = "credit" if delta > 0 else "debit"
        prev_balance = r["closing_balance"]


def _extract_summary(pdf) -> dict | None:
    """Pull opening balance, closing balance, totals from the STATEMENT SUMMARY."""
    for page in pdf.pages[-3:]:
        text = page.extract_text() or ""
        if "STATEMENTSUMMARY" not in text and "STATEMENT SUMMARY" not in text:
            continue
        lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
        for i, ln in enumerate(lines):
            if "OpeningBalance" in ln or "Opening Balance" in ln:
                for nxt in lines[i + 1 : i + 5]:
                    nums = re.findall(r"[\d,]+\.\d{2}|\d+", nxt)
                    if len(nums) >= 6:
                        try:
                            return {
                                "opening_balance": _to_amount(nums[0]),
                                "debit_count": int(nums[1]),
                                "credit_count": int(nums[2]),
                                "debits_total": _to_amount(nums[3]),
                                "credits_total": _to_amount(nums[4]),
                                "closing_balance": _to_amount(nums[5]),
                            }
                        except (ValueError, IndexError):
                            continue
    return None


class HDFCBankPDFAdapter(BankAdapter):
    source_type = "hdfc_pdf"
    parser_version = "0.3.0"

    def can_handle(self, file_path: Path) -> bool:
        try:
            with pdfplumber.open(file_path) as pdf:
                first = pdf.pages[0].extract_text() or ""
            return "HDFC" in first.upper()
        except Exception:
            return False

    def parse(self, file_path: Path, password: str | None = None) -> ParseResult:
        unlocked = unlock_pdf(file_path, password)
        result = ParseResult()
        rows: list[dict] = []
        current_narration_lines: list[str] = []
        current_row: dict | None = None
        in_footer_zone = False  # True after a stop-line is seen, until next txn line

        def flush():
            if current_row is not None:
                current_row["narration_full"] = " ".join(current_narration_lines).strip()
                rows.append(current_row)

        with pdfplumber.open(unlocked) as pdf:
            summary = _extract_summary(pdf)
            opening_balance = summary["opening_balance"] if summary else None

            for page in pdf.pages:
                text = page.extract_text() or ""
                # Reset footer zone at the top of each page; the next valid txn
                # line will turn it off, but headers at the top of the new page
                # should still be skipped.
                in_footer_zone = True

                for raw_line in text.splitlines():
                    line = raw_line.strip()
                    if not line:
                        continue

                    parsed = _parse_txn_line(line)
                    if parsed is not None:
                        # New transaction. Close any pending one, open this one,
                        # exit footer zone.
                        flush()
                        current_row = parsed
                        current_narration_lines = [parsed["narration_first_line"]]
                        in_footer_zone = False
                        continue

                    # Not a transaction line. If it's a stop-line OR we're already
                    # in the footer zone, do not append; close current row and
                    # skip until next transaction.
                    if _is_stop_line(line) or in_footer_zone:
                        if current_row is not None:
                            flush()
                            current_row = None
                            current_narration_lines = []
                        in_footer_zone = True
                        continue

                    # Otherwise it's narration continuation for the current row.
                    if current_row is not None:
                        current_narration_lines.append(line)

            flush()

        if not rows:
            result.warnings.append(
                "No transaction rows detected. Layout may differ from expected."
            )
            return result

        _infer_directions(rows, opening_balance)

        for r in rows:
            result.transactions.append(
                ParsedTransaction(
                    txn_date=r["txn_date"],
                    value_date=r["value_date"],
                    txn_time=None,
                    description=r["narration_full"],
                    amount=r["amount"],
                    direction=r["direction"],
                    balance_after=r["closing_balance"],
                    reference_id=r["reference_id"],
                    upi_id=None,
                    raw_row=r,
                )
            )

        # Verification warnings
        if summary:
            total_debits = sum(t.amount for t in result.transactions if t.direction == "debit")
            total_credits = sum(t.amount for t in result.transactions if t.direction == "credit")
            if abs(total_debits - summary["debits_total"]) > 1:
                result.warnings.append(
                    f"Debits total mismatch: parsed {total_debits:.2f} vs summary {summary['debits_total']:.2f}"
                )
            if abs(total_credits - summary["credits_total"]) > 1:
                result.warnings.append(
                    f"Credits total mismatch: parsed {total_credits:.2f} vs summary {summary['credits_total']:.2f}"
                )
            count_d = sum(1 for t in result.transactions if t.direction == "debit")
            count_c = sum(1 for t in result.transactions if t.direction == "credit")
            if count_d != summary["debit_count"] or count_c != summary["credit_count"]:
                result.warnings.append(
                    f"Count mismatch: parsed {count_d}D/{count_c}C vs summary "
                    f"{summary['debit_count']}D/{summary['credit_count']}C"
                )

        return result
